---

- name: check if servers and config server length are equal
  fail:
    msg: "Mismatch in number of servers and oai nodes: {{ oai.servers|length }} vs {{ groups['oai_nodes']|length }}"
  when: oai.servers|length != groups['oai_nodes']|length

- name: delete {{ oai.docker.container.gnb_image }} container
  community.docker.docker_container:
    name: "oai-gnb"
    state: absent
  when: inventory_hostname in groups['oai_nodes']
  become: true

- name: remove /tmp/oai-gnb.conf
  file:
    path: "/tmp/oai-gnb.conf"
    state: absent
  when: inventory_hostname in groups['oai_nodes']
  become: true

- name: remove {{ oai.docker.container.gnb_image }} image
  community.docker.docker_image:
    name: "{{ oai.docker.container.gnb_image }}"
    state: absent
    force_absent: true
  when: inventory_hostname in groups['oai_nodes']
  become: true
