---

- name: install oai/docker
  import_tasks: roles/docker/tasks/install.yml
  tags: install

- name: uninstall oai/docker
  import_tasks: roles/docker/tasks/uninstall.yml
  tags: uninstall

- name: start oai/dockers
  import_tasks: roles/docker/tasks/start.yml
  tags: start

- name: stop oai/dockers
  import_tasks: roles/docker/tasks/stop.yml
  tags: stop
